//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Actions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Actions"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""53fb1fd5-82fb-4bea-914e-868f58a22623"",
            ""actions"": [
                {
                    ""name"": ""primary"",
                    ""type"": ""Button"",
                    ""id"": ""7e7a3faf-3c8b-4b30-b35a-2b450937d709"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""secondary"",
                    ""type"": ""Button"",
                    ""id"": ""e8261a06-7736-49ad-96cf-7aa008551933"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""ce933f27-8d2a-4d49-b5a4-d5a76c46c7cc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""7166bf88-feeb-4cff-be3d-dbaaeb228cf8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouse_position"",
                    ""type"": ""Value"",
                    ""id"": ""e53d4118-9fdb-4543-8b2a-5723484886ec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""mouse_scroll"",
                    ""type"": ""Value"",
                    ""id"": ""ce9503d0-f2a2-4424-b0a5-7c3814713cf3"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""do_raycast"",
                    ""type"": ""Button"",
                    ""id"": ""c87ca580-0b2b-49f4-b423-f59fcd6e08be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""show_pointer_over_game_obj"",
                    ""type"": ""Button"",
                    ""id"": ""967c0718-6971-4b43-a827-0ff26ad2d40e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""220c4a8d-309b-46ed-9ba8-c85bc3a77a4d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""primary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61fefd1d-2c54-472f-99bb-2cad490e7642"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""secondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""244af88a-2a70-4128-bd58-57c24e86f044"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""63f89e20-7d65-4ff8-a00f-71b9deb8b151"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""75c3a912-4d94-4376-980c-07c9d45025ee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3e601fbc-6375-4b34-9261-306e096a350c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7b513bef-37dd-45ec-8d7e-6c663253c5da"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5a41ccde-87bb-4861-846a-1db82f14a5b4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fd83a50-72cc-4fd8-9575-5abb58f4a747"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouse_position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e466efe-c6b8-43c8-9c2c-6085833be8e7"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouse_scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c7b412e-0395-43b2-9760-e7268038ded3"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""do_raycast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be8cc622-8830-4da8-85cb-299dde0b5dea"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""show_pointer_over_game_obj"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ui"",
            ""id"": ""5d203d61-a4da-441a-8cf1-a742c06c089d"",
            ""actions"": [
                {
                    ""name"": ""toggle_inventory"",
                    ""type"": ""Button"",
                    ""id"": ""e60c4c82-7cc6-40fd-86d2-53acbf7bea32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggle_dialog"",
                    ""type"": ""Button"",
                    ""id"": ""280c9589-f489-454a-87ea-b24cc9e645c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""next"",
                    ""type"": ""Button"",
                    ""id"": ""268b869d-d5d0-4255-abc2-eb20bb42894e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""previous"",
                    ""type"": ""Button"",
                    ""id"": ""dc1a67e5-2a04-4d08-a3b6-3f5568acca79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hold_next"",
                    ""type"": ""Button"",
                    ""id"": ""2658e792-b90f-4b0b-877a-a8803e9a01c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hold_prev"",
                    ""type"": ""Button"",
                    ""id"": ""c4ca0855-a945-4afc-b8d1-c54a5b9eb1a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot1"",
                    ""type"": ""Button"",
                    ""id"": ""0e3450c2-1ede-4ae3-a94c-885121ecde64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot2"",
                    ""type"": ""Button"",
                    ""id"": ""8020ef76-edaa-422a-88c2-fb2b6a4dcf2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot3"",
                    ""type"": ""Button"",
                    ""id"": ""040ef9ad-0b0e-4c85-94f3-a5427c27260b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot4"",
                    ""type"": ""Button"",
                    ""id"": ""e327853a-3099-45e6-9f36-fa48fe41a6fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot5"",
                    ""type"": ""Button"",
                    ""id"": ""b657c228-9701-4fa1-bb43-2bb40cee6a57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot6"",
                    ""type"": ""Button"",
                    ""id"": ""6e20f1a4-2070-443e-a6c8-837809699b6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot7"",
                    ""type"": ""Button"",
                    ""id"": ""1ece3ee8-c58b-4307-840b-d713c12fb0e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot8"",
                    ""type"": ""Button"",
                    ""id"": ""1da7acaa-33d8-4ba9-8436-716426765663"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slot9"",
                    ""type"": ""Button"",
                    ""id"": ""e42a975a-4487-4293-a657-850ae3c2d7a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7f5696e-06c4-4fd3-b4ac-d69405fd0c93"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggle_inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""476c564c-414d-4c36-8a95-45f3ee544e82"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggle_dialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9cb640a-10d9-4e1d-acc9-cfac4ef6c099"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hold_next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8777a217-8607-409f-9007-687063add93d"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hold_prev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ed1ea7c-b105-492a-bbaa-577248f3bd78"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d11c24c-bdcd-46e4-8485-bb8722dcd8b3"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""previous"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecffe936-bce6-4330-9b56-c2bfbd12b84d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3901c8d-ada7-4f52-a425-7d165ee6523f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""decbebe0-fbe5-46a8-8bf1-2896c686e651"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""591f2ac8-8af1-4edf-a57c-2c45b8cdcb1d"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44c3f924-4746-4042-864e-50f1f0f5bfe3"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a05fc7f9-fc0f-49bf-84fa-57e98ce042dd"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8583b46c-9aed-4c49-8c39-9892557a095a"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fb501eb-be8e-4a09-848f-592444be4fb7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d8b66e7-99bd-4275-a35b-2d97bba58035"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slot9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""visualiser"",
            ""id"": ""c9c16945-db18-4622-8269-b8c006b3d3f0"",
            ""actions"": [
                {
                    ""name"": ""spawn_carver"",
                    ""type"": ""Button"",
                    ""id"": ""b0965384-54b6-429f-8a13-ea16987d630d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""step_to_next_node"",
                    ""type"": ""Button"",
                    ""id"": ""017be021-97bc-4423-873e-a3ca18ef4b58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouse_position"",
                    ""type"": ""Value"",
                    ""id"": ""871172a2-eb39-4225-a405-be7ffd60cb40"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""step"",
                    ""type"": ""Button"",
                    ""id"": ""01b209cf-5185-4d40-ba14-42b67c9beb51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select_next"",
                    ""type"": ""Button"",
                    ""id"": ""81fe9570-bfe9-4806-9758-86e3afda6c8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select_prev"",
                    ""type"": ""Button"",
                    ""id"": ""2ef9af4c-f14e-4bae-a7cd-5ba775999196"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toggle_line"",
                    ""type"": ""Button"",
                    ""id"": ""e8d49ec6-099d-4585-807a-12235939ed01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7fb26946-c38b-4407-908e-c143c024196c"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spawn_carver"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c01f356-d246-4ce3-a941-1132830e4b8b"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""step_to_next_node"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3adde43c-ad06-418d-9e1a-81fdbe99f28d"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouse_position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09a02450-7aa0-413c-93f5-cbc3b22df661"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""step"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f60cb246-1327-4397-856b-81e7c43f2d57"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select_next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13bae6bc-74a2-4145-93da-8fa710abdc98"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select_prev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5829cf02-f51e-4588-ac58-45769326a652"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toggle_line"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_primary = m_gameplay.FindAction("primary", throwIfNotFound: true);
        m_gameplay_secondary = m_gameplay.FindAction("secondary", throwIfNotFound: true);
        m_gameplay_move = m_gameplay.FindAction("move", throwIfNotFound: true);
        m_gameplay_jump = m_gameplay.FindAction("jump", throwIfNotFound: true);
        m_gameplay_mouse_position = m_gameplay.FindAction("mouse_position", throwIfNotFound: true);
        m_gameplay_mouse_scroll = m_gameplay.FindAction("mouse_scroll", throwIfNotFound: true);
        m_gameplay_do_raycast = m_gameplay.FindAction("do_raycast", throwIfNotFound: true);
        m_gameplay_show_pointer_over_game_obj = m_gameplay.FindAction("show_pointer_over_game_obj", throwIfNotFound: true);
        // ui
        m_ui = asset.FindActionMap("ui", throwIfNotFound: true);
        m_ui_toggle_inventory = m_ui.FindAction("toggle_inventory", throwIfNotFound: true);
        m_ui_toggle_dialog = m_ui.FindAction("toggle_dialog", throwIfNotFound: true);
        m_ui_next = m_ui.FindAction("next", throwIfNotFound: true);
        m_ui_previous = m_ui.FindAction("previous", throwIfNotFound: true);
        m_ui_hold_next = m_ui.FindAction("hold_next", throwIfNotFound: true);
        m_ui_hold_prev = m_ui.FindAction("hold_prev", throwIfNotFound: true);
        m_ui_slot1 = m_ui.FindAction("slot1", throwIfNotFound: true);
        m_ui_slot2 = m_ui.FindAction("slot2", throwIfNotFound: true);
        m_ui_slot3 = m_ui.FindAction("slot3", throwIfNotFound: true);
        m_ui_slot4 = m_ui.FindAction("slot4", throwIfNotFound: true);
        m_ui_slot5 = m_ui.FindAction("slot5", throwIfNotFound: true);
        m_ui_slot6 = m_ui.FindAction("slot6", throwIfNotFound: true);
        m_ui_slot7 = m_ui.FindAction("slot7", throwIfNotFound: true);
        m_ui_slot8 = m_ui.FindAction("slot8", throwIfNotFound: true);
        m_ui_slot9 = m_ui.FindAction("slot9", throwIfNotFound: true);
        // visualiser
        m_visualiser = asset.FindActionMap("visualiser", throwIfNotFound: true);
        m_visualiser_spawn_carver = m_visualiser.FindAction("spawn_carver", throwIfNotFound: true);
        m_visualiser_step_to_next_node = m_visualiser.FindAction("step_to_next_node", throwIfNotFound: true);
        m_visualiser_mouse_position = m_visualiser.FindAction("mouse_position", throwIfNotFound: true);
        m_visualiser_step = m_visualiser.FindAction("step", throwIfNotFound: true);
        m_visualiser_select_next = m_visualiser.FindAction("select_next", throwIfNotFound: true);
        m_visualiser_select_prev = m_visualiser.FindAction("select_prev", throwIfNotFound: true);
        m_visualiser_toggle_line = m_visualiser.FindAction("toggle_line", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_gameplay_primary;
    private readonly InputAction m_gameplay_secondary;
    private readonly InputAction m_gameplay_move;
    private readonly InputAction m_gameplay_jump;
    private readonly InputAction m_gameplay_mouse_position;
    private readonly InputAction m_gameplay_mouse_scroll;
    private readonly InputAction m_gameplay_do_raycast;
    private readonly InputAction m_gameplay_show_pointer_over_game_obj;
    public struct GameplayActions
    {
        private @Actions m_Wrapper;
        public GameplayActions(@Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @primary => m_Wrapper.m_gameplay_primary;
        public InputAction @secondary => m_Wrapper.m_gameplay_secondary;
        public InputAction @move => m_Wrapper.m_gameplay_move;
        public InputAction @jump => m_Wrapper.m_gameplay_jump;
        public InputAction @mouse_position => m_Wrapper.m_gameplay_mouse_position;
        public InputAction @mouse_scroll => m_Wrapper.m_gameplay_mouse_scroll;
        public InputAction @do_raycast => m_Wrapper.m_gameplay_do_raycast;
        public InputAction @show_pointer_over_game_obj => m_Wrapper.m_gameplay_show_pointer_over_game_obj;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @primary.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimary;
                @primary.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimary;
                @primary.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimary;
                @secondary.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondary;
                @secondary.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondary;
                @secondary.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondary;
                @move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @mouse_position.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_position;
                @mouse_position.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_position;
                @mouse_position.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_position;
                @mouse_scroll.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_scroll;
                @mouse_scroll.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_scroll;
                @mouse_scroll.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse_scroll;
                @do_raycast.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDo_raycast;
                @do_raycast.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDo_raycast;
                @do_raycast.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDo_raycast;
                @show_pointer_over_game_obj.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShow_pointer_over_game_obj;
                @show_pointer_over_game_obj.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShow_pointer_over_game_obj;
                @show_pointer_over_game_obj.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShow_pointer_over_game_obj;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @primary.started += instance.OnPrimary;
                @primary.performed += instance.OnPrimary;
                @primary.canceled += instance.OnPrimary;
                @secondary.started += instance.OnSecondary;
                @secondary.performed += instance.OnSecondary;
                @secondary.canceled += instance.OnSecondary;
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
                @mouse_position.started += instance.OnMouse_position;
                @mouse_position.performed += instance.OnMouse_position;
                @mouse_position.canceled += instance.OnMouse_position;
                @mouse_scroll.started += instance.OnMouse_scroll;
                @mouse_scroll.performed += instance.OnMouse_scroll;
                @mouse_scroll.canceled += instance.OnMouse_scroll;
                @do_raycast.started += instance.OnDo_raycast;
                @do_raycast.performed += instance.OnDo_raycast;
                @do_raycast.canceled += instance.OnDo_raycast;
                @show_pointer_over_game_obj.started += instance.OnShow_pointer_over_game_obj;
                @show_pointer_over_game_obj.performed += instance.OnShow_pointer_over_game_obj;
                @show_pointer_over_game_obj.canceled += instance.OnShow_pointer_over_game_obj;
            }
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);

    // ui
    private readonly InputActionMap m_ui;
    private IUiActions m_UiActionsCallbackInterface;
    private readonly InputAction m_ui_toggle_inventory;
    private readonly InputAction m_ui_toggle_dialog;
    private readonly InputAction m_ui_next;
    private readonly InputAction m_ui_previous;
    private readonly InputAction m_ui_hold_next;
    private readonly InputAction m_ui_hold_prev;
    private readonly InputAction m_ui_slot1;
    private readonly InputAction m_ui_slot2;
    private readonly InputAction m_ui_slot3;
    private readonly InputAction m_ui_slot4;
    private readonly InputAction m_ui_slot5;
    private readonly InputAction m_ui_slot6;
    private readonly InputAction m_ui_slot7;
    private readonly InputAction m_ui_slot8;
    private readonly InputAction m_ui_slot9;
    public struct UiActions
    {
        private @Actions m_Wrapper;
        public UiActions(@Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @toggle_inventory => m_Wrapper.m_ui_toggle_inventory;
        public InputAction @toggle_dialog => m_Wrapper.m_ui_toggle_dialog;
        public InputAction @next => m_Wrapper.m_ui_next;
        public InputAction @previous => m_Wrapper.m_ui_previous;
        public InputAction @hold_next => m_Wrapper.m_ui_hold_next;
        public InputAction @hold_prev => m_Wrapper.m_ui_hold_prev;
        public InputAction @slot1 => m_Wrapper.m_ui_slot1;
        public InputAction @slot2 => m_Wrapper.m_ui_slot2;
        public InputAction @slot3 => m_Wrapper.m_ui_slot3;
        public InputAction @slot4 => m_Wrapper.m_ui_slot4;
        public InputAction @slot5 => m_Wrapper.m_ui_slot5;
        public InputAction @slot6 => m_Wrapper.m_ui_slot6;
        public InputAction @slot7 => m_Wrapper.m_ui_slot7;
        public InputAction @slot8 => m_Wrapper.m_ui_slot8;
        public InputAction @slot9 => m_Wrapper.m_ui_slot9;
        public InputActionMap Get() { return m_Wrapper.m_ui; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UiActions set) { return set.Get(); }
        public void SetCallbacks(IUiActions instance)
        {
            if (m_Wrapper.m_UiActionsCallbackInterface != null)
            {
                @toggle_inventory.started -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_inventory;
                @toggle_inventory.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_inventory;
                @toggle_inventory.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_inventory;
                @toggle_dialog.started -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_dialog;
                @toggle_dialog.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_dialog;
                @toggle_dialog.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnToggle_dialog;
                @next.started -= m_Wrapper.m_UiActionsCallbackInterface.OnNext;
                @next.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnNext;
                @next.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnNext;
                @previous.started -= m_Wrapper.m_UiActionsCallbackInterface.OnPrevious;
                @previous.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnPrevious;
                @previous.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnPrevious;
                @hold_next.started -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_next;
                @hold_next.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_next;
                @hold_next.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_next;
                @hold_prev.started -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_prev;
                @hold_prev.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_prev;
                @hold_prev.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnHold_prev;
                @slot1.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot1;
                @slot1.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot1;
                @slot1.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot1;
                @slot2.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot2;
                @slot2.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot2;
                @slot2.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot2;
                @slot3.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot3;
                @slot3.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot3;
                @slot3.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot3;
                @slot4.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot4;
                @slot4.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot4;
                @slot4.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot4;
                @slot5.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot5;
                @slot5.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot5;
                @slot5.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot5;
                @slot6.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot6;
                @slot6.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot6;
                @slot6.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot6;
                @slot7.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot7;
                @slot7.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot7;
                @slot7.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot7;
                @slot8.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot8;
                @slot8.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot8;
                @slot8.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot8;
                @slot9.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot9;
                @slot9.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot9;
                @slot9.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSlot9;
            }
            m_Wrapper.m_UiActionsCallbackInterface = instance;
            if (instance != null)
            {
                @toggle_inventory.started += instance.OnToggle_inventory;
                @toggle_inventory.performed += instance.OnToggle_inventory;
                @toggle_inventory.canceled += instance.OnToggle_inventory;
                @toggle_dialog.started += instance.OnToggle_dialog;
                @toggle_dialog.performed += instance.OnToggle_dialog;
                @toggle_dialog.canceled += instance.OnToggle_dialog;
                @next.started += instance.OnNext;
                @next.performed += instance.OnNext;
                @next.canceled += instance.OnNext;
                @previous.started += instance.OnPrevious;
                @previous.performed += instance.OnPrevious;
                @previous.canceled += instance.OnPrevious;
                @hold_next.started += instance.OnHold_next;
                @hold_next.performed += instance.OnHold_next;
                @hold_next.canceled += instance.OnHold_next;
                @hold_prev.started += instance.OnHold_prev;
                @hold_prev.performed += instance.OnHold_prev;
                @hold_prev.canceled += instance.OnHold_prev;
                @slot1.started += instance.OnSlot1;
                @slot1.performed += instance.OnSlot1;
                @slot1.canceled += instance.OnSlot1;
                @slot2.started += instance.OnSlot2;
                @slot2.performed += instance.OnSlot2;
                @slot2.canceled += instance.OnSlot2;
                @slot3.started += instance.OnSlot3;
                @slot3.performed += instance.OnSlot3;
                @slot3.canceled += instance.OnSlot3;
                @slot4.started += instance.OnSlot4;
                @slot4.performed += instance.OnSlot4;
                @slot4.canceled += instance.OnSlot4;
                @slot5.started += instance.OnSlot5;
                @slot5.performed += instance.OnSlot5;
                @slot5.canceled += instance.OnSlot5;
                @slot6.started += instance.OnSlot6;
                @slot6.performed += instance.OnSlot6;
                @slot6.canceled += instance.OnSlot6;
                @slot7.started += instance.OnSlot7;
                @slot7.performed += instance.OnSlot7;
                @slot7.canceled += instance.OnSlot7;
                @slot8.started += instance.OnSlot8;
                @slot8.performed += instance.OnSlot8;
                @slot8.canceled += instance.OnSlot8;
                @slot9.started += instance.OnSlot9;
                @slot9.performed += instance.OnSlot9;
                @slot9.canceled += instance.OnSlot9;
            }
        }
    }
    public UiActions @ui => new UiActions(this);

    // visualiser
    private readonly InputActionMap m_visualiser;
    private IVisualiserActions m_VisualiserActionsCallbackInterface;
    private readonly InputAction m_visualiser_spawn_carver;
    private readonly InputAction m_visualiser_step_to_next_node;
    private readonly InputAction m_visualiser_mouse_position;
    private readonly InputAction m_visualiser_step;
    private readonly InputAction m_visualiser_select_next;
    private readonly InputAction m_visualiser_select_prev;
    private readonly InputAction m_visualiser_toggle_line;
    public struct VisualiserActions
    {
        private @Actions m_Wrapper;
        public VisualiserActions(@Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @spawn_carver => m_Wrapper.m_visualiser_spawn_carver;
        public InputAction @step_to_next_node => m_Wrapper.m_visualiser_step_to_next_node;
        public InputAction @mouse_position => m_Wrapper.m_visualiser_mouse_position;
        public InputAction @step => m_Wrapper.m_visualiser_step;
        public InputAction @select_next => m_Wrapper.m_visualiser_select_next;
        public InputAction @select_prev => m_Wrapper.m_visualiser_select_prev;
        public InputAction @toggle_line => m_Wrapper.m_visualiser_toggle_line;
        public InputActionMap Get() { return m_Wrapper.m_visualiser; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VisualiserActions set) { return set.Get(); }
        public void SetCallbacks(IVisualiserActions instance)
        {
            if (m_Wrapper.m_VisualiserActionsCallbackInterface != null)
            {
                @spawn_carver.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSpawn_carver;
                @spawn_carver.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSpawn_carver;
                @spawn_carver.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSpawn_carver;
                @step_to_next_node.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep_to_next_node;
                @step_to_next_node.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep_to_next_node;
                @step_to_next_node.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep_to_next_node;
                @mouse_position.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnMouse_position;
                @mouse_position.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnMouse_position;
                @mouse_position.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnMouse_position;
                @step.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep;
                @step.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep;
                @step.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnStep;
                @select_next.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_next;
                @select_next.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_next;
                @select_next.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_next;
                @select_prev.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_prev;
                @select_prev.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_prev;
                @select_prev.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnSelect_prev;
                @toggle_line.started -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnToggle_line;
                @toggle_line.performed -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnToggle_line;
                @toggle_line.canceled -= m_Wrapper.m_VisualiserActionsCallbackInterface.OnToggle_line;
            }
            m_Wrapper.m_VisualiserActionsCallbackInterface = instance;
            if (instance != null)
            {
                @spawn_carver.started += instance.OnSpawn_carver;
                @spawn_carver.performed += instance.OnSpawn_carver;
                @spawn_carver.canceled += instance.OnSpawn_carver;
                @step_to_next_node.started += instance.OnStep_to_next_node;
                @step_to_next_node.performed += instance.OnStep_to_next_node;
                @step_to_next_node.canceled += instance.OnStep_to_next_node;
                @mouse_position.started += instance.OnMouse_position;
                @mouse_position.performed += instance.OnMouse_position;
                @mouse_position.canceled += instance.OnMouse_position;
                @step.started += instance.OnStep;
                @step.performed += instance.OnStep;
                @step.canceled += instance.OnStep;
                @select_next.started += instance.OnSelect_next;
                @select_next.performed += instance.OnSelect_next;
                @select_next.canceled += instance.OnSelect_next;
                @select_prev.started += instance.OnSelect_prev;
                @select_prev.performed += instance.OnSelect_prev;
                @select_prev.canceled += instance.OnSelect_prev;
                @toggle_line.started += instance.OnToggle_line;
                @toggle_line.performed += instance.OnToggle_line;
                @toggle_line.canceled += instance.OnToggle_line;
            }
        }
    }
    public VisualiserActions @visualiser => new VisualiserActions(this);
    public interface IGameplayActions
    {
        void OnPrimary(InputAction.CallbackContext context);
        void OnSecondary(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMouse_position(InputAction.CallbackContext context);
        void OnMouse_scroll(InputAction.CallbackContext context);
        void OnDo_raycast(InputAction.CallbackContext context);
        void OnShow_pointer_over_game_obj(InputAction.CallbackContext context);
    }
    public interface IUiActions
    {
        void OnToggle_inventory(InputAction.CallbackContext context);
        void OnToggle_dialog(InputAction.CallbackContext context);
        void OnNext(InputAction.CallbackContext context);
        void OnPrevious(InputAction.CallbackContext context);
        void OnHold_next(InputAction.CallbackContext context);
        void OnHold_prev(InputAction.CallbackContext context);
        void OnSlot1(InputAction.CallbackContext context);
        void OnSlot2(InputAction.CallbackContext context);
        void OnSlot3(InputAction.CallbackContext context);
        void OnSlot4(InputAction.CallbackContext context);
        void OnSlot5(InputAction.CallbackContext context);
        void OnSlot6(InputAction.CallbackContext context);
        void OnSlot7(InputAction.CallbackContext context);
        void OnSlot8(InputAction.CallbackContext context);
        void OnSlot9(InputAction.CallbackContext context);
    }
    public interface IVisualiserActions
    {
        void OnSpawn_carver(InputAction.CallbackContext context);
        void OnStep_to_next_node(InputAction.CallbackContext context);
        void OnMouse_position(InputAction.CallbackContext context);
        void OnStep(InputAction.CallbackContext context);
        void OnSelect_next(InputAction.CallbackContext context);
        void OnSelect_prev(InputAction.CallbackContext context);
        void OnToggle_line(InputAction.CallbackContext context);
    }
}
